export default [
  {
    title: 'Dashboard',
    pathName: 'Dashboard',
    accessible: true,
    icon: 'th-large',
    activeWhen: ['Dashboard'],
  },
  {
    title: 'Deposit',
    pathName: 'DepositList',
    accessible: true,
    icon: 'sack',
    activeWhen: [
      'DepositList',
      'DepositNew',
      'DepositSuccess',
      'DepositInstructions',
      'DepositConfirmation',
    ],
  },
  {
    title: 'Transfer',
    pathName: 'TransferList',
    accessible: true,
    icon: 'inbox-out',
    activeWhen: [
      'TransferList',
      'TransferBeneficiary',
      'TransferAmount',
      'TransferConfirm',
      'TransferSuccess',
    ],
  },
  {
    title: 'Receive',
    pathName: 'ReceiveList',
    accessible: true,
    icon: 'inbox-in',
    activeWhen: [
      'ReceiveList',
      'ReceiveBeneficiary',
      'ReceiveAmount',
      'ReceiveConfirm',
      'ReceiveSuccess',
    ],
  },
  {
    title: 'Withdraw',
    pathName: 'WithdrawList',
    accessible: true,
    icon: 'wallet',
    activeWhen: [
      'WithdrawList',
      'WithdrawNew',
      'WithdrawConfirm',
      'WithdrawSuccess',
    ],
  },
  {
    title: 'Reports',
    pathName: 'Reports',
    accessible: true,
    icon: 'history',
    activeWhen: ['Reports'],
  },
  {
    title: 'Support',
    pathName: 'Support',
    accessible: true,
    icon: 'user-headset',
    activeWhen: ['Support'],
  },
]
